# Generated by Django 2.2.5 on 2021-05-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.FloatField(max_length=10)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='img/producto')),
                ('estado', models.CharField(blank=True, default='1', max_length=2, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
    ]
