# Generated by Django 2.2.5 on 2021-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodoenvio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/comprobante'),
        ),
    ]
