# Generated by Django 2.2.5 on 2021-06-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_metodoenvio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='disponibilidad',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
