# Generated by Django 2.2.5 on 2021-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_totalpagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/comprobante'),
        ),
    ]
