# Generated by Django 2.2.5 on 2021-06-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estadoComprobante',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
