# Generated by Django 2.2.5 on 2021-06-06 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_pedido_estadocomprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estadoComprobante',
            new_name='estadoc',
        ),
    ]
