# Generated by Django 2.2.5 on 2021-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20210605_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
