# Generated by Django 2.2.5 on 2021-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_pedido_tipo_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodoenvio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='metodoenvio',
            name='direccion',
            field=models.CharField(default='local', max_length=200, null=True),
        ),
    ]
