# Generated by Django 2.2.5 on 2021-06-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_auto_20210606_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodoenvio',
            name='ciudad',
            field=models.CharField(blank=True, default='local', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metodoenvio',
            name='direccion',
            field=models.CharField(blank=True, default='local', max_length=200, null=True),
        ),
    ]
