# Generated by Django 2.2.5 on 2021-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
