# Generated by Django 2.2.5 on 2021-06-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_imagen'),
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria'),
        ),
    ]
