# Generated by Django 2.2.5 on 2021-07-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0003_auto_20210606_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='id_categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria'),
        ),
    ]
