# Generated by Django 2.2.5 on 2021-06-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
