# Generated by Django 2.2.5 on 2021-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_usuario',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
    ]
