# Generated by Django 2.2.5 on 2021-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=100, unique=True)),
                ('numero_cuenta', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(blank=True, default='1', max_length=2, null=True)),
            ],
        ),
    ]
