# Generated by Django 2.2.5 on 2021-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoscuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscuenta',
            name='nombre_persona',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
